title: Simar's Portfolio
description: Welcome to my portfolio, where I demonstrate my expertise and insights through various projects and learning experiences. This page highlights my journey in cybersecurity, showcasing practical skills and achievements.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
