title: Simar's Portfolio
description: A technology aficionado with a real passion for exploring new tools and technologies. I’m always learning and enjoy diving into different areas of tech, from troubleshooting to building projects that keep my skills sharp. This portfolio is a collection of what I've been working on and discovering along the way. I’m excited to keep growing, sharing my progress, and connecting with others who share this same curiosity for all things tech!
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
